version: '3'

services:
  postgres:
    image: 'postgres:13'
    container_name: 'java-postgres'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=bmw_user'
      - 'POSTGRES_PASSWORD=bmw_user'
      - 'POSTGRES_DB=bmw_db'